global:
  scrape_interval: 1s

scrape_configs:
#  - job_name: 'prometheus'
#    scrape_interval: 5s
#    static_configs:
#      - targets: ['myapi:6003']
#    metrics_path: '/tam-metrics'
  - job_name: 'pushgateway'
    honor_labels: true
    scrape_interval: 5s
    static_configs:
      - targets: [ 'pushgateway:9091' ]
