{
 "title": "libp2p-pubsub simulator",
 "description": "libp2p-pubsub simulator and it's state machines (sim,sim-p0,sim-p1,sim-p2,ps-0,ps-1,ps-2)",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Simulator", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Topics",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    { "expr": "sim_peers_per_topic", "legendFormat": "Avg peers per topic", "query": "sim_peers_per_topic" },
    { "expr": "sim_topics", "legendFormat": "Topics", "query": "sim_topics" }
   ]
  },
  {
   "title": "Messages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    { "expr": "sim_msgs_recv", "legendFormat": "Delivered msgs", "query": "sim_msgs_recv" },
    { "expr": "sim_msgs_miss", "legendFormat": "Missed msgs", "query": "sim_msgs_miss" }
   ]
  },
  {
   "title": "Peers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    { "expr": "sim_friends", "legendFormat": "Friendships", "query": "sim_friends" },
    { "expr": "sim_peers", "legendFormat": "Peers", "query": "sim_peers" },
    { "expr": "sim_peer_with_topics", "legendFormat": "Peers with topics", "query": "sim_peer_with_topics" }
   ]
  },
  {
   "title": "Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    { "expr": "sim_connections", "legendFormat": "Connections", "query": "sim_connections" },
    { "expr": "sim_streams", "legendFormat": "Streams", "query": "sim_streams" }
   ]
  },
  { "title": "Machine: sim", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Transition changes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    { "expr": "mach_sim_queue_size", "legendFormat": "Queue size", "query": "mach_sim_queue_size" },
    { "expr": "mach_sim_tx_tick", "legendFormat": "Tx ticks", "query": "mach_sim_tx_tick" },
    { "expr": "mach_sim_steps_amount", "legendFormat": "Number of tx steps", "query": "mach_sim_steps_amount" },
    { "expr": "mach_sim_handlers_amount", "legendFormat": "Called handlers", "query": "mach_sim_handlers_amount" },
    { "expr": "mach_sim_states_added", "legendFormat": "States added", "query": "mach_sim_states_added" },
    { "expr": "mach_sim_states_removed", "legendFormat": "States removed", "query": "mach_sim_states_removed" },
    { "expr": "mach_sim_touched", "legendFormat": "States touched", "query": "mach_sim_touched" }
   ]
  },
  {
   "title": "Machine states",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    { "expr": "mach_sim_ref_states_amount", "legendFormat": "States referenced in relations", "query": "mach_sim_ref_states_amount" },
    { "expr": "mach_sim_relations_amount", "legendFormat": "Relations", "query": "mach_sim_relations_amount" },
    { "expr": "mach_sim_states_active_amount", "legendFormat": "States active", "query": "mach_sim_states_active_amount" },
    {
     "expr": "mach_sim_states_inactive_amount",
     "legendFormat": "States inactive",
     "query": "mach_sim_states_inactive_amount"
    }
   ]
  },
  {
   "title": "Transition time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    { "expr": "mach_sim_tx_time / 1000", "legendFormat": "Tx time (ms)", "query": "mach_sim_tx_time / 1000" }
   ]
  },
  {
   "title": "Average transition time",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    { "expr": "mach_sim_tx_time / 1000", "legendFormat": "Tx time (ms)", "query": "mach_sim_tx_time / 1000" }
   ]
  },
  {
   "title": "Exceptions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "targets": [
    { "expr": "mach_sim_exceptions_count", "legendFormat": "Exceptions", "query": "mach_sim_exceptions_count" }
   ]
  },
  { "title": "Machine: sim_p0", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "Transition changes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "targets": [
    { "expr": "mach_sim_p0_queue_size", "legendFormat": "Queue size", "query": "mach_sim_p0_queue_size" },
    { "expr": "mach_sim_p0_tx_tick", "legendFormat": "Tx ticks", "query": "mach_sim_p0_tx_tick" },
    { "expr": "mach_sim_p0_steps_amount", "legendFormat": "Number of tx steps", "query": "mach_sim_p0_steps_amount" },
    { "expr": "mach_sim_p0_handlers_amount", "legendFormat": "Called handlers", "query": "mach_sim_p0_handlers_amount" },
    { "expr": "mach_sim_p0_states_added", "legendFormat": "States added", "query": "mach_sim_p0_states_added" },
    { "expr": "mach_sim_p0_states_removed", "legendFormat": "States removed", "query": "mach_sim_p0_states_removed" },
    { "expr": "mach_sim_p0_touched", "legendFormat": "States touched", "query": "mach_sim_p0_touched" }
   ]
  },
  {
   "title": "Machine states",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "targets": [
    { "expr": "mach_sim_p0_ref_states_amount", "legendFormat": "States referenced in relations", "query": "mach_sim_p0_ref_states_amount" },
    { "expr": "mach_sim_p0_relations_amount", "legendFormat": "Relations", "query": "mach_sim_p0_relations_amount" },
    {
     "expr": "mach_sim_p0_states_active_amount",
     "legendFormat": "States active",
     "query": "mach_sim_p0_states_active_amount"
    },
    {
     "expr": "mach_sim_p0_states_inactive_amount",
     "legendFormat": "States inactive",
     "query": "mach_sim_p0_states_inactive_amount"
    }
   ]
  },
  {
   "title": "Transition time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
   "targets": [
    { "expr": "mach_sim_p0_tx_time / 1000", "legendFormat": "Tx time (ms)", "query": "mach_sim_p0_tx_time / 1000" }
   ]
  },
  {
   "title": "Average transition time",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
   "targets": [
    { "expr": "mach_sim_p0_tx_time / 1000", "legendFormat": "Tx time (ms)", "query": "mach_sim_p0_tx_time / 1000" }
   ]
  },
  {
   "title": "Exceptions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
   "targets": [
    { "expr": "mach_sim_p0_exceptions_count", "legendFormat": "Exceptions", "query": "mach_sim_p0_exceptions_count" }
   ]
  },
  { "title": "Machine: sim_p1", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 69 } },
  {
   "title": "Transition changes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 70 },
   "targets": [
    { "expr": "mach_sim_p1_queue_size", "legendFormat": "Queue size", "query": "mach_sim_p1_queue_size" },
    { "expr": "mach_sim_p1_tx_tick", "legendFormat": "Tx ticks", "query": "mach_sim_p1_tx_tick" },
    { "expr": "mach_sim_p1_steps_amount", "legendFormat": "Number of tx steps", "query": "mach_sim_p1_steps_amount" },
    { "expr": "mach_sim_p1_handlers_amount", "legendFormat": "Called handlers", "query": "mach_sim_p1_handlers_amount" },
    { "expr": "mach_sim_p1_states_added", "legendFormat": "States added", "query": "mach_sim_p1_states_added" },
    { "expr": "mach_sim_p1_states_removed", "legendFormat": "States removed", "query": "mach_sim_p1_states_removed" },
    { "expr": "mach_sim_p1_touched", "legendFormat": "States touched", "query": "mach_sim_p1_touched" }
   ]
  },
  {
   "title": "Machine states",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 70 },
   "targets": [
    { "expr": "mach_sim_p1_ref_states_amount", "legendFormat": "States referenced in relations", "query": "mach_sim_p1_ref_states_amount" },
    { "expr": "mach_sim_p1_relations_amount", "legendFormat": "Relations", "query": "mach_sim_p1_relations_amount" },
    {
     "expr": "mach_sim_p1_states_active_amount",
     "legendFormat": "States active",
     "query": "mach_sim_p1_states_active_amount"
    },
    {
     "expr": "mach_sim_p1_states_inactive_amount",
     "legendFormat": "States inactive",
     "query": "mach_sim_p1_states_inactive_amount"
    }
   ]
  },
  {
   "title": "Transition time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 78 },
   "targets": [
    { "expr": "mach_sim_p1_tx_time / 1000", "legendFormat": "Tx time (ms)", "query": "mach_sim_p1_tx_time / 1000" }
   ]
  },
  {
   "title": "Average transition time",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 78 },
   "targets": [
    { "expr": "mach_sim_p1_tx_time / 1000", "legendFormat": "Tx time (ms)", "query": "mach_sim_p1_tx_time / 1000" }
   ]
  },
  {
   "title": "Exceptions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 86 },
   "targets": [
    { "expr": "mach_sim_p1_exceptions_count", "legendFormat": "Exceptions", "query": "mach_sim_p1_exceptions_count" }
   ]
  },
  { "title": "Machine: sim_p2", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 95 } },
  {
   "title": "Transition changes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 96 },
   "targets": [
    { "expr": "mach_sim_p2_queue_size", "legendFormat": "Queue size", "query": "mach_sim_p2_queue_size" },
    { "expr": "mach_sim_p2_tx_tick", "legendFormat": "Tx ticks", "query": "mach_sim_p2_tx_tick" },
    { "expr": "mach_sim_p2_steps_amount", "legendFormat": "Number of tx steps", "query": "mach_sim_p2_steps_amount" },
    { "expr": "mach_sim_p2_handlers_amount", "legendFormat": "Called handlers", "query": "mach_sim_p2_handlers_amount" },
    { "expr": "mach_sim_p2_states_added", "legendFormat": "States added", "query": "mach_sim_p2_states_added" },
    { "expr": "mach_sim_p2_states_removed", "legendFormat": "States removed", "query": "mach_sim_p2_states_removed" },
    { "expr": "mach_sim_p2_touched", "legendFormat": "States touched", "query": "mach_sim_p2_touched" }
   ]
  },
  {
   "title": "Machine states",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 96 },
   "targets": [
    { "expr": "mach_sim_p2_ref_states_amount", "legendFormat": "States referenced in relations", "query": "mach_sim_p2_ref_states_amount" },
    { "expr": "mach_sim_p2_relations_amount", "legendFormat": "Relations", "query": "mach_sim_p2_relations_amount" },
    {
     "expr": "mach_sim_p2_states_active_amount",
     "legendFormat": "States active",
     "query": "mach_sim_p2_states_active_amount"
    },
    {
     "expr": "mach_sim_p2_states_inactive_amount",
     "legendFormat": "States inactive",
     "query": "mach_sim_p2_states_inactive_amount"
    }
   ]
  },
  {
   "title": "Transition time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 104 },
   "targets": [
    { "expr": "mach_sim_p2_tx_time / 1000", "legendFormat": "Tx time (ms)", "query": "mach_sim_p2_tx_time / 1000" }
   ]
  },
  {
   "title": "Average transition time",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 104 },
   "targets": [
    { "expr": "mach_sim_p2_tx_time / 1000", "legendFormat": "Tx time (ms)", "query": "mach_sim_p2_tx_time / 1000" }
   ]
  },
  {
   "title": "Exceptions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 112 },
   "targets": [
    { "expr": "mach_sim_p2_exceptions_count", "legendFormat": "Exceptions", "query": "mach_sim_p2_exceptions_count" }
   ]
  },
  { "title": "Machine: ps_0", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 121 } },
  {
   "title": "Transition changes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 122 },
   "targets": [
    { "expr": "mach_ps_0_queue_size", "legendFormat": "Queue size", "query": "mach_ps_0_queue_size" },
    { "expr": "mach_ps_0_tx_tick", "legendFormat": "Tx ticks", "query": "mach_ps_0_tx_tick" },
    { "expr": "mach_ps_0_steps_amount", "legendFormat": "Number of tx steps", "query": "mach_ps_0_steps_amount" },
    { "expr": "mach_ps_0_handlers_amount", "legendFormat": "Called handlers", "query": "mach_ps_0_handlers_amount" },
    { "expr": "mach_ps_0_states_added", "legendFormat": "States added", "query": "mach_ps_0_states_added" },
    { "expr": "mach_ps_0_states_removed", "legendFormat": "States removed", "query": "mach_ps_0_states_removed" },
    { "expr": "mach_ps_0_touched", "legendFormat": "States touched", "query": "mach_ps_0_touched" }
   ]
  },
  {
   "title": "Machine states",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 122 },
   "targets": [
    { "expr": "mach_ps_0_ref_states_amount", "legendFormat": "States referenced in relations", "query": "mach_ps_0_ref_states_amount" },
    { "expr": "mach_ps_0_relations_amount", "legendFormat": "Relations", "query": "mach_ps_0_relations_amount" },
    { "expr": "mach_ps_0_states_active_amount", "legendFormat": "States active", "query": "mach_ps_0_states_active_amount" },
    {
     "expr": "mach_ps_0_states_inactive_amount",
     "legendFormat": "States inactive",
     "query": "mach_ps_0_states_inactive_amount"
    }
   ]
  },
  {
   "title": "Transition time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 130 },
   "targets": [
    { "expr": "mach_ps_0_tx_time / 1000", "legendFormat": "Tx time (ms)", "query": "mach_ps_0_tx_time / 1000" }
   ]
  },
  {
   "title": "Average transition time",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 130 },
   "targets": [
    { "expr": "mach_ps_0_tx_time / 1000", "legendFormat": "Tx time (ms)", "query": "mach_ps_0_tx_time / 1000" }
   ]
  },
  {
   "title": "Exceptions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 138 },
   "targets": [
    { "expr": "mach_ps_0_exceptions_count", "legendFormat": "Exceptions", "query": "mach_ps_0_exceptions_count" }
   ]
  },
  { "title": "Machine: ps_1", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 147 } },
  {
   "title": "Transition changes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 148 },
   "targets": [
    { "expr": "mach_ps_1_queue_size", "legendFormat": "Queue size", "query": "mach_ps_1_queue_size" },
    { "expr": "mach_ps_1_tx_tick", "legendFormat": "Tx ticks", "query": "mach_ps_1_tx_tick" },
    { "expr": "mach_ps_1_steps_amount", "legendFormat": "Number of tx steps", "query": "mach_ps_1_steps_amount" },
    { "expr": "mach_ps_1_handlers_amount", "legendFormat": "Called handlers", "query": "mach_ps_1_handlers_amount" },
    { "expr": "mach_ps_1_states_added", "legendFormat": "States added", "query": "mach_ps_1_states_added" },
    { "expr": "mach_ps_1_states_removed", "legendFormat": "States removed", "query": "mach_ps_1_states_removed" },
    { "expr": "mach_ps_1_touched", "legendFormat": "States touched", "query": "mach_ps_1_touched" }
   ]
  },
  {
   "title": "Machine states",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 148 },
   "targets": [
    { "expr": "mach_ps_1_ref_states_amount", "legendFormat": "States referenced in relations", "query": "mach_ps_1_ref_states_amount" },
    { "expr": "mach_ps_1_relations_amount", "legendFormat": "Relations", "query": "mach_ps_1_relations_amount" },
    { "expr": "mach_ps_1_states_active_amount", "legendFormat": "States active", "query": "mach_ps_1_states_active_amount" },
    {
     "expr": "mach_ps_1_states_inactive_amount",
     "legendFormat": "States inactive",
     "query": "mach_ps_1_states_inactive_amount"
    }
   ]
  },
  {
   "title": "Transition time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 156 },
   "targets": [
    { "expr": "mach_ps_1_tx_time / 1000", "legendFormat": "Tx time (ms)", "query": "mach_ps_1_tx_time / 1000" }
   ]
  },
  {
   "title": "Average transition time",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 156 },
   "targets": [
    { "expr": "mach_ps_1_tx_time / 1000", "legendFormat": "Tx time (ms)", "query": "mach_ps_1_tx_time / 1000" }
   ]
  },
  {
   "title": "Exceptions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 164 },
   "targets": [
    { "expr": "mach_ps_1_exceptions_count", "legendFormat": "Exceptions", "query": "mach_ps_1_exceptions_count" }
   ]
  },
  { "title": "Machine: ps_2", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 173 } },
  {
   "title": "Transition changes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 174 },
   "targets": [
    { "expr": "mach_ps_2_queue_size", "legendFormat": "Queue size", "query": "mach_ps_2_queue_size" },
    { "expr": "mach_ps_2_tx_tick", "legendFormat": "Tx ticks", "query": "mach_ps_2_tx_tick" },
    { "expr": "mach_ps_2_steps_amount", "legendFormat": "Number of tx steps", "query": "mach_ps_2_steps_amount" },
    { "expr": "mach_ps_2_handlers_amount", "legendFormat": "Called handlers", "query": "mach_ps_2_handlers_amount" },
    { "expr": "mach_ps_2_states_added", "legendFormat": "States added", "query": "mach_ps_2_states_added" },
    { "expr": "mach_ps_2_states_removed", "legendFormat": "States removed", "query": "mach_ps_2_states_removed" },
    { "expr": "mach_ps_2_touched", "legendFormat": "States touched", "query": "mach_ps_2_touched" }
   ]
  },
  {
   "title": "Machine states",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 174 },
   "targets": [
    { "expr": "mach_ps_2_ref_states_amount", "legendFormat": "States referenced in relations", "query": "mach_ps_2_ref_states_amount" },
    { "expr": "mach_ps_2_relations_amount", "legendFormat": "Relations", "query": "mach_ps_2_relations_amount" },
    { "expr": "mach_ps_2_states_active_amount", "legendFormat": "States active", "query": "mach_ps_2_states_active_amount" },
    {
     "expr": "mach_ps_2_states_inactive_amount",
     "legendFormat": "States inactive",
     "query": "mach_ps_2_states_inactive_amount"
    }
   ]
  },
  {
   "title": "Transition time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 182 },
   "targets": [
    { "expr": "mach_ps_2_tx_time / 1000", "legendFormat": "Tx time (ms)", "query": "mach_ps_2_tx_time / 1000" }
   ]
  },
  {
   "title": "Average transition time",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 182 },
   "targets": [
    { "expr": "mach_ps_2_tx_time / 1000", "legendFormat": "Tx time (ms)", "query": "mach_ps_2_tx_time / 1000" }
   ]
  },
  {
   "title": "Exceptions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 190 },
   "targets": [
    { "expr": "mach_ps_2_exceptions_count", "legendFormat": "Exceptions", "query": "mach_ps_2_exceptions_count" }
   ]
  }
 ]
}